# Minimal golangci-lint configuration with standard presets
# For more options, see: https://golangci-lint.run/usage/configuration/

version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  default: standard
  enable:
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - unused
  - typecheck
  - nlreturn
  - whitespace
  - wsl

formatters:
  enable:
  - gofmt
  - goimports
