
networks:
  mainnet:
    api_url: https://zetachain.blockpi.network/lcd/v1/public
    poll_interval: 10s
    audiences: # Should match the keys in audience_config
    - mainnet_operators
    - testnet_operators
    - developers
  testnet:
    api_url: https://zetachain-athens.blockpi.network/lcd/v1/public
    poll_interval: 5s
    audiences:
    - testnet_operators
    - developers
# another_net:
#   api_url: https://anothernet.com

audience_config:
  mainnet_operators:
    channels:
      discord:
      - "1398006827903357150" # Discord channel ID for mainnet
      slack:
      - "${SLACK_MAINNET_WEBHOOK}"
      telegram:
      - "-1002380605871" # zetachain-mainnet-notifs channel
  testnet_operators:
    channels:
      discord:
      - "1397738539202117712" # Discord channel ID for testnet
      slack:
      - "${SLACK_TESTNET_WEBHOOK}"
      telegram:
      - "-1002765533620" # zetachain-testnet-operators group
      - "-1002599116582" # zetachain-testnet-notifs channel
  developers:
    channels:
      discord:
      - "1398249758371348501"

events:
  proposals:
    filters:
      message_types:
      - "/cosmos.upgrade.v1beta1.MsgSoftwareUpgrade"
      - "/cosmos.upgrade.v1beta1.MsgCancelUpgrade"

notifiers:
  discord:
    bot_token: "${DISCORD_BOT_TOKEN}" # Use environment variable for security
  telegram:
    bot_token: "${TELEGRAM_BOT_TOKEN}"

storage:
  filename: file-db.yaml

logging:
  level: info # trace, debug, info, warn, error
  format: console # console/text or json
